"""empty message

Revision ID: 12486c7a46c
Revises: 33de160c2f4a
Create Date: 2014-10-21 17:08:46.950806

"""

# revision identifiers, used by Alembic.
revision = '12486c7a46c'
down_revision = '33de160c2f4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
