"""empty message

Revision ID: 1a667070fbc
Revises: 7ef971eb5d1
Create Date: 2015-02-11 16:39:11.939676

"""

# revision identifiers, used by Alembic.
revision = '1a667070fbc'
down_revision = '7ef971eb5d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
