"""empty message

Revision ID: 1b1e0a65a517
Revises: 52fda8c732ff
Create Date: 2014-10-20 12:15:10.798322

"""

# revision identifiers, used by Alembic.
revision = '1b1e0a65a517'
down_revision = '52fda8c732ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('imagesLinks', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'imagesLinks')
    ### end Alembic commands ###
