"""empty message

Revision ID: 213c32f515ab
Revises: 461739726a44
Create Date: 2015-02-05 15:28:34.489695

"""

# revision identifiers, used by Alembic.
revision = '213c32f515ab'
down_revision = '461739726a44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
