"""empty message

Revision ID: 29012d4679af
Revises: a210dda0746
Create Date: 2015-02-05 14:25:15.230198

"""

# revision identifiers, used by Alembic.
revision = '29012d4679af'
down_revision = 'a210dda0746'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=100), nullable=True))
    op.drop_column('user', u'first_name')
    op.drop_column('user', u'last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column(u'first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    ### end Alembic commands ###
