"""empty message

Revision ID: 2e9c3b9e7e33
Revises: 33912b08b84e
Create Date: 2014-11-14 08:58:27.546837

"""

# revision identifiers, used by Alembic.
revision = '2e9c3b9e7e33'
down_revision = '33912b08b84e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
