"""empty message

Revision ID: 33912b08b84e
Revises: 12486c7a46c
Create Date: 2014-10-28 18:13:33.301596

"""

# revision identifiers, used by Alembic.
revision = '33912b08b84e'
down_revision = '12486c7a46c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('codeLink', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('cover_photo', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'cover_photo')
    op.drop_column('project', 'codeLink')
    ### end Alembic commands ###
