"""empty message

Revision ID: 33de160c2f4a
Revises: 50033ac5d5a0
Create Date: 2014-10-21 16:34:43.561915

"""

# revision identifiers, used by Alembic.
revision = '33de160c2f4a'
down_revision = '50033ac5d5a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
