"""empty message

Revision ID: 352fd8c3c613
Revises: 39d5972b48b
Create Date: 2015-07-14 23:29:05.928865

"""

# revision identifiers, used by Alembic.
revision = '352fd8c3c613'
down_revision = '39d5972b48b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'date')
    ### end Alembic commands ###
