"""empty message

Revision ID: 371ad33f91af
Revises: 57fdd21420bf
Create Date: 2014-10-20 17:37:06.316613

"""

# revision identifiers, used by Alembic.
revision = '371ad33f91af'
down_revision = '57fdd21420bf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', u'date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(u'date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
