"""empty message

Revision ID: 39d5972b48b
Revises: 4374ea02738b
Create Date: 2015-07-14 23:27:34.506585

"""

# revision identifiers, used by Alembic.
revision = '39d5972b48b'
down_revision = '4374ea02738b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
