"""empty message

Revision ID: 3e30196a8a24
Revises: 81f44c239bb
Create Date: 2014-10-20 17:26:07.923998

"""

# revision identifiers, used by Alembic.
revision = '3e30196a8a24'
down_revision = '81f44c239bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
