"""empty message

Revision ID: 3f156fb6224
Revises: beffa456ec
Create Date: 2014-10-20 17:29:06.708872

"""

# revision identifiers, used by Alembic.
revision = '3f156fb6224'
down_revision = 'beffa456ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
