"""empty message

Revision ID: 401ba0430d2e
Revises: 36d703c4541a
Create Date: 2014-10-19 18:06:55.380417

"""

# revision identifiers, used by Alembic.
revision = '401ba0430d2e'
down_revision = '36d703c4541a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('externalLink', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'externalLink')
    ### end Alembic commands ###
