"""empty message

Revision ID: 4374ea02738b
Revises: 595f60cee86a
Create Date: 2015-07-14 23:26:21.319497

"""

# revision identifiers, used by Alembic.
revision = '4374ea02738b'
down_revision = '595f60cee86a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', u'date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(u'date', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
