"""empty message

Revision ID: 461739726a44
Revises: 29012d4679af
Create Date: 2015-02-05 15:22:08.658502

"""

# revision identifiers, used by Alembic.
revision = '461739726a44'
down_revision = '29012d4679af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
