"""empty message

Revision ID: 471f4a1e8776
Revises: None
Create Date: 2014-11-21 15:28:11.656016

"""

# revision identifiers, used by Alembic.
revision = '471f4a1e8776'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'comment')
    op.drop_table(u'user')
    op.add_column('project', sa.Column('codeLink', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('cover_photo', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'cover_photo')
    op.drop_column('project', 'codeLink')
    op.create_table(u'user',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('user_id_seq'::regclass)", nullable=False),
    sa.Column(u'firstname', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column(u'lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column(u'email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column(u'picture_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column(u'username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column(u'password', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'user_pkey')
    )
    op.create_table(u'comment',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('comment_id_seq'::regclass)", nullable=False),
    sa.Column(u'user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column(u'updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'comment_pkey')
    )
    ### end Alembic commands ###
