"""empty message

Revision ID: 4eb3c079ed39
Revises: 2e9c3b9e7e33
Create Date: 2014-11-14 08:59:21.853270

"""

# revision identifiers, used by Alembic.
revision = '4eb3c079ed39'
down_revision = '2e9c3b9e7e33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
