"""empty message

Revision ID: 4ec0a0144b34
Revises: 213c32f515ab
Create Date: 2015-02-05 15:29:44.309680

"""

# revision identifiers, used by Alembic.
revision = '4ec0a0144b34'
down_revision = '213c32f515ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
