"""empty message

Revision ID: 50033ac5d5a0
Revises: 371ad33f91af
Create Date: 2014-10-20 17:37:58.609217

"""

# revision identifiers, used by Alembic.
revision = '50033ac5d5a0'
down_revision = '371ad33f91af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'date')
    ### end Alembic commands ###
