"""empty message

Revision ID: 529fff5a9fee
Revises: 55fcad2cd852
Create Date: 2014-10-20 16:23:46.829780

"""

# revision identifiers, used by Alembic.
revision = '529fff5a9fee'
down_revision = '55fcad2cd852'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'date')
    ### end Alembic commands ###
