"""empty message

Revision ID: 52fda8c732ff
Revises: 401ba0430d2e
Create Date: 2014-10-19 20:40:57.826338

"""

# revision identifiers, used by Alembic.
revision = '52fda8c732ff'
down_revision = '401ba0430d2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('projectType', sa.String(length=255), nullable=True))
    op.drop_column('project', u'project_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(u'project_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('project', 'projectType')
    ### end Alembic commands ###
