"""empty message

Revision ID: 55fcad2cd852
Revises: 1b1e0a65a517
Create Date: 2014-10-20 16:18:11.878631

"""

# revision identifiers, used by Alembic.
revision = '55fcad2cd852'
down_revision = '1b1e0a65a517'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('snippet', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'snippet')
    ### end Alembic commands ###
