"""empty message

Revision ID: 57fdd21420bf
Revises: 3f156fb6224
Create Date: 2014-10-20 17:32:40.775676

"""

# revision identifiers, used by Alembic.
revision = '57fdd21420bf'
down_revision = '3f156fb6224'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
