"""empty message

Revision ID: 595f60cee86a
Revises: None
Create Date: 2015-07-14 23:03:50.796940

"""

# revision identifiers, used by Alembic.
revision = '595f60cee86a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
