"""empty message

Revision ID: 7ef971eb5d1
Revises: 4ec0a0144b34
Create Date: 2015-02-11 16:38:43.044951

"""

# revision identifiers, used by Alembic.
revision = '7ef971eb5d1'
down_revision = '4ec0a0144b34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
