"""empty message

Revision ID: 81f44c239bb
Revises: d748c8c3699
Create Date: 2014-10-20 17:22:56.958195

"""

# revision identifiers, used by Alembic.
revision = '81f44c239bb'
down_revision = 'd748c8c3699'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
