"""empty message

Revision ID: a210dda0746
Revises: 55f8daad49b4
Create Date: 2015-02-04 23:06:42.356677

"""

# revision identifiers, used by Alembic.
revision = 'a210dda0746'
down_revision = '55f8daad49b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=20), nullable=True))
    op.create_index(u'ix_user_email', 'user', ['email'], unique=True)
    op.create_index(u'ix_user_username', 'user', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_user_username', table_name='user')
    op.drop_index(u'ix_user_email', table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'registered_on')
    ### end Alembic commands ###
