"""empty message

Revision ID: beffa456ec
Revises: 3e30196a8a24
Create Date: 2014-10-20 17:27:53.398288

"""

# revision identifiers, used by Alembic.
revision = 'beffa456ec'
down_revision = '3e30196a8a24'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
