"""empty message

Revision ID: d748c8c3699
Revises: 529fff5a9fee
Create Date: 2014-10-20 17:00:49.546458

"""

# revision identifiers, used by Alembic.
revision = 'd748c8c3699'
down_revision = '529fff5a9fee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
